### ISSUE TITLE
Site loads slowly :(

### ISSUE THREAD

**Issue by pesehr** [LinuxFest/LinuxFestival9#11]
if you clean your cache, you will see the site loads slowly.

**Comment by 1995parham** [comment]
I am coming ... I will do my best 😢

**Comment by 1995parham** [comment]
https://gist.github.com/SlicedSilver/f2e93a5995f84d9cd512

**Comment by pesehr** [comment]
😭😭😭

**Comment by 1995parham** [comment]
Done

**Comment by 1995parham** [comment]
Loading page was added.

**Comment by pesehr** [comment]
the site is not loading any more 😭😭😭

**Comment by pi0** [comment]
Not sure but it may be also server related. I'm going to host it somewhere else to compare.

**Comment by 1995parham** [comment]
Thank you very much poooooya ! 😍

**Comment by pi0** [comment]
No changes :) Adding loading splash would be best idea for now :))

**Comment by 1995parham** [comment]
I added the loading page 👍

**Comment by 1995parham** [comment]
I think we are done for now ...
