### ISSUE TITLE
Disable Browser Sync

### ISSUE THREAD

**Issue by 1995parham** [LinuxFest/LinuxFestival9#5]

**Comment by pi0** [comment]
Not sure why to disable this. If this just makes problem in production, we may also check if `process.env.NODE_ENV` is not `production` and optimize things for that.

**Comment by 1995parham** [comment]
I replaced it with gulp-connect because I can disable auto-reload in gulp-connect.

**Comment by pi0** [comment]
So can we entirely remove dependency?

**Comment by 1995parham** [comment]
Yes we can 😄
